### ISSUE TITLE
asks for password before keys are generated

### ISSUE THREAD

**Issue by mjplacroix** [ethereum/eth2.0-deposit-cli#109]
I run the deposit.exe
Asks how many validators
Asks for language
Asks which testnet
Immediately asks for "password that secures your validator keystore(s)"
A) I haven't generated anything yet
B) I'm unable to type anything in this space

Help/Thoughts?

**Comment by CarlBeek** [comment]
We should make the prompt clearer, it is asking for a password that will be used in the future to secure your keys. Also, you probably typing, it just doesn't show you what has been typed to prevent your password from being displayed in the clear.

**Comment by mjplacroix** [comment]
Gotcha - thanks for clearing that up. Good to go. Working on getting my full setup by the end of the week.
