### ISSUE TITLE
Description of --chain flag needs updating

### ISSUE THREAD

**Issue by SpyderChristian** [ethereum/eth2.0-deposit-cli#150]
On the page it currently says "Please make sure you have set --chain mainnet for _**Mainnet testnet**_, otherwise the deposit will be invalid."

It appears that Medalla was replaced with Mainnet but they never erased the word "testnet".  I bold/italicized this in the text above. The issue is in page https://launchpad.ethereum.org/generate-keys under step 2.

**Comment by hwwhww** [comment]
Thanks for the report @SpyderChristian! It was fixed in https://github.com/ethereum/eth2.0-deposit/pull/245 and will be included in the next Launchpad release.
