### ISSUE TITLE
Unclear why "amd64" appears in the binaries for eth2.0-deposit-cli v1.0.0

### ISSUE THREAD

**Issue by A2be** [ethereum/eth2.0-deposit-cli#154]
"macOS amd64", "Linux amd64", and "Windows amd64" appear as the description for each of the three available binaries for the  v1.0.0 (hash:  9310de0...) version of the Eth2 deposit contract CLI.

**Whatever limitation is expressed or implied by the adjective "amd64" ought to be made more explicit**; else the Ethereum newbie or non-technical Ethereum user will be confused.

Does it mean that "only AMD64 chipsets are supported"? 
... only Advanced Micro Devices processors? 
Or would these binaries be expected to run successfully on, say, a standard Intel PC chipset that is common in the Win PC world?

**Comment by hwwhww** [comment]
Hi @A2be, sorry for the very late reply!

Currently, we use `pyinstaller` to build the binaries. But unfortunately, `pyinstaller` doesn't support cross-compile, so the binary built on amd64 machine doesn't work on arm64 machine.

Closing this issue now. Let me know if you want to re-open it.
