### ISSUE TITLE
mnemonic with extra word

### ISSUE THREAD

**Issue by reiven** [ethereum/eth2.0-deposit-cli#169]
Looks like if you use a 25-word mnemonic you get 
```eth2deposit.exceptions.ValidationError: That is not a valid mnemonic, please check for typos.```

Let say you want to use mnemonic from a hardware wallet and use passphase: this will give you 25 (or even more) words.
Why limit to 24?

Maybe 24 should be the min but not the max?

**Comment by CarlBeek** [comment]
According to the standard behind [BIP39], a mnemonic can be either 12, 15, 18, 21, or 24 word long ([see table here](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic)).

If you have a mnemonic that is not one of those lengths either:
* the mnemonic doesn't follow the industry standards (I have yet to see a tool that generates mnemonics that does this)
* there is a mnemonic password that used when the mnemonic was first created, and what you are thinking of as the 25th word, is actually this password. If this is the case, you can use `./deposit.sh existing_mnemonic --mnemonic-password yourPasswordHere`. Please be careful though, the forgetting the password or typing it in incorrectly will result in you not being able to recover your keys.

**Comment by reiven** [comment]
Good, thanks
