### ISSUE TITLE
Beacon chain P2P error faild to find peers

### ISSUE THREAD

**Issue by Robelsan** [ethereum/eth2.0-deposit-cli#173]
Hello everyone,
i've an issue with the beaconchain mainnet related to the p2p error attached, can anyone help with this?

Thank you so much in advance

![p2p error beaconchian](https://user-images.githubusercontent.com/75683847/101501527-26806080-3970-11eb-97e4-fd19415acd34.PNG)

**Comment by hwwhww** [comment]
Wrong repository.

Please visit https://github.com/prysmaticlabs/prysm or [their discord](https://discord.gg/CTYGPUJ) or [ethstaker discord](https://invite.gg/ethstaker). Thanks!
