### ISSUE TITLE
Deposit cli tool - Ledger NanoX app Incompatibility

### ISSUE THREAD

**Issue by robbtezos** [ethereum/eth2.0-deposit-cli#179]
-->  ******* RESOLVED ******
Note: The problem seems to have been resolved. It is an issue with the 3rd party validator services not passing proper incremented path for each of the multiple validators. You may want to check with your validator service if they had fixed it.
<--

There is an incompatibility problem with generating multiple validators and their withdrawal credentials in the same run of the deposit cli tool vs what the various validator services provide using ledger X app services.

When you create multiple validators, the withdrawal keys do not match in their tools as compared to the deposit cli tool -- except for the index 0 value.

With or without adding a passphrase to your ledger mnemonic does not matter. 

Test it with multiple validators creation in the same run and compare the withdrawal keys/credentials across all the tools with what the launchpad deposit cli tool provides. This more or less points to a ledger X eth2 app issue. Even with different addresses of eth1 in same HD order, ledger provides the same withdrawal key credentials. This flaw seems to be carried into the generation of multiple withdrawal keys when you create multiple validators at same time with these services.

 It is quite important that we be independently able to withdraw and generate keystore files independent of depending on ledger and trezor to provide appropriate drivers in appropriate time whenever it is 2 years from now.

 If we do not address these incompatibilities now, future withdrawal tools from Eth2 foundation or the implementation of the withdrawal functions could cause further issue and loss of funds.

Some additional context can be had from the interaction with /r/btchip and others at reddit on this matter and may give some insights to you:

https://www.reddit.com/r/ethstaker/comments/kyw2x7/passphrase_25th_word_to_secure_the_seed/gko4lgl/

Further elaboration of issues in the comments below:

As a testimony to this issue, i attach the following from one of the developers. Hope someone can egg on Ledger to fix this issue with their eth2 app.

--->
101ca7 1 point 9 hours ago
Hi, thanks for replying and experimenting.

I looked through your github issues and you are correct that the issue lies with Ledger.

I was able to find the menmonic EIP spec here https://eips.ethereum.org/EIPS/eip-2334

And it clearly outlines that the withdrawal path is also incremented for each validator (which makes it impossible to have the same withdrawal key for different validators derived from the same mnemonic) it looks like Ledger has created a non conformant implementation.

I would strongly advise against using passphrases because of this. Of course you can generate the keystore and withdrawal keys either way but this non-conformance could cause a lot of headaches in the future.

<-----

It needs to be pointed out that the issue is not with using passphrases. It happens without a passphrase being used also. Ledger implementation seems to assume that each mnemonic or mnemonic+passphrase corresponds to same withdrawal credential without regard to the incrementing it down the heirarchy.

Steps to replicate:
1) Use your ledger mnemonic 24 word phrase (optionally add in the passphrase if you want with mnemonic-password parameter in the deposit.exe tool.

2) Choose to create multiple validators (say index 0 to 3) in same run.

    Generate the deposit.json, keystore.json file / validator_keys using deposit.tool 

3) Generate the same validator_keys / deposit.json/keystore.json files using any of the validator services that let your use your ledger nano X directly and create the keys. (Example -- wallet.allnodes.com/eth2/generate
 
 Following instructions specific to allnodes process..
   a) Connect your ledger nano X with ethereum app
   b) Select any address on the same heiarchical path and click "show eth2 credentials"
   c) Select another address in the heirarchy and click show eth2 credentials
    d) you will see they all point to same eth2 withdrawal credentials irrespective of which eth1 address it is coming from
       (This is a  flaw with ledger app which I believe also creeps into the validator_keys/withdrawal credentials creation process)
    e) To be more sure of what i said above, you may want to double check with similar funcition in staked.us where you can 
        connect your ledger nano X and derive the withdrawal key public address corresponding to the eth1 address you choose.
        You will see in staked.us also that all addresses in the eth1 heiarchy give the same withdrawal public key. 
        So this is not an isolated issue with allnodes or staked.us or any other service which interfaces with nano X.. They are 
         dependent on ledger nano X to provide the withdrawal key credentials and ledger nanoX eth2 app is not incrementing the
         path for each address in the eth1 heirarchy.
     f) continuing on with allnodes tool, you can go ahead and create say 3 nodes with starting index 0 and provide the same encryption password to encrypt the json files with. (deposit.json, keystore.json).. Once you are finished with this you will have your validator_keys directory with the json files created and ready to go.

    4) Now compare the deposit.json and keystore.json files in the validator_keys files directories as generated in step 2 and in step 3.

     5) You will find the differences due to the incompatible implementation in the deposit.json files -- with the withdrawal credentials non matching in both processes.
         When you compare the keystore.json files, the "params":["iv": "xyz....xyz"] fields also do not match.

I hope some of you can help resolve this issue working with Ledger company on this. Before it gets too late to address and causes any potential loss of funds or inconvenience.

**Comment by robbtezos** [comment]
Sorry i take back my some of my comments here. I see that the --mnemonic-password option in deposit.exe command line provides that option. It being not mentioned in launchpad documentation may have been the issue. Generally people do not clearly about this option now.

But however, when creating multiple validators in same deposit.exe command, all the validators have different withdrawal-credentials. But the tools that are seen in staked, allnodes and other services use one single withdraw credential across all the validators defined in a single deposit file.  Just wondering how to force that in the deposit-cli tool or why their tools are not conforming to the same standard of generating multiple withdrawal-credentials.

For instance choosing any of the eth1 HD addresses in stakewise forces the same  withdrawal-credentials across all the addresses in the heirarchy.  Not sure if we will run into problem later down the road if we have a difference in the way these withdrawal-credentials are generated.

**Comment by robbtezos** [comment]
I have asked ledger (btchip at reddit) to look into this and provide his comments.. hopefully we get some clarification

 btchip sent just now

May be you could look at this and provide your comments

https://github.com/ethereum/eth2.0-deposit-cli/issues/179

The launchpad deposit cli obviously allows us to specify a passphrase called as --mnemonic-password option. But it is differing in some ways from how you may be deriving the withdrawal-credentials in your ledger nano app.

I see that wallet.allnodes.com, staked.us, and others who generate withdraw credentials from nanoX generate the same credential for all multiple validators in the same batch. Also all the eth1 HD addresses that you see within a passphrase option in say mew, etc., are all generating the same withdrawal-credential. I do not know if this is a simplification of the ledger app. And if so, how could we reconcile this with what the official launchpad cli tool is generating as different withdrawal-credentials for multiple validators generated at same time. At some point in time, we may want to say move from ledger on to a non-ledger or other hardware wallet and things should be uniform i believe..

**Comment by NStifter** [comment]
From your description it appears that the ledger nano app is not conformant to https://eips.ethereum.org/EIPS/eip-2334 and only uses the first withdrawal path m/12381/3600/0/0 for subsequent validators

**Comment by robbtezos** [comment]
Our further testing of this issue revealed the following.. Note all the data generated for the ledger X implementation came from the wallet.allnodes.com/eth2/generate tool and its comparison with the launchpad cli tool. Similar problem potentially exists with staked.us and quite probably many other validator service providers depending on ledger nanoX eth2 drivers.

Everyone who is interefacing to ledger nano X generates the same withdrawal public key and credentials currently whether or not they use the passphrases. (That is even if you pick up different HD heiarchical addresses of eth1 address space you end up with same withdraw credential) . This could be a problem later down the road potentially for withdrawals from eth2 if withdrawals get mapped to the corresponding eth1 addresses.

ISSUES WITH ALLNODES USING LEDGERX WALLET  ETH2/GENERATE
(Difference in params: "iv" values in all keystore.json files.. while the launchpad deposit cli tool generates same params ["iv": xxxxxxx] for all indexes.
NOTE THAT THE LAUNCHPAD TOOL GENERATES SAME PARAMS IV -- VALUES AND ALLNODES LEDGERX TOOL GENERATES DIFFERENT PARAMS IV values..
----> keystore.json files values when using allnodes ledger X tool : <---------
path: m/12381/3600/0/0/0
"params": ["iv": "722b.....982" ]

path: m/12381/3600/1/0/0
"params":["iv": "96a7....65ab"]

path: m/12381/3600/2/0/0
"params": ["iv": "50fad4cc......db18" ]

path: m/12381/3600/3/0/0
"params":["iv": "a74dd...7a38"]

--> keystore.json files values when using launchpad-deposit-cli tool: <---
path: m/12381/3600/0/0/0
"params": ["iv": "51ee87....f18d" ]

path: m/12381/3600/1/0/0
"params":["iv": "51ee87....f18d"]

path: m/12381/3600/2/0/0
"params": ["iv": "51ee87....f18d" ]

path: m/12381/3600/3/0/0
"params":["iv": "51ee87....f18d"]


================================
Differences in deposit.json withdrawal credentials when using ledger nano X allnodes tool vs launchpad deposit-cli tool using same mnemonics..

NOTE THAT ONLY INDEX 0 withdrawal credentials are common in both cases and others are different.
---> Following are deposit.json withdraw-cred when using  allnodes ledger X generation tool: <------ 
deposit.json index 0 - pubkey "a87..3df7" withdraw-cred "00d3eee...e289b"
deposit.json index 1 - pubkey "b8d..9790" withdraw-cred "00d3eee...e289b"
deposit.json index 2 - pubkey "83e..91c0" withdraw-cred "00d3eee...e289b"
deposit.json index 3 - pubkey "8db..6665" withdraw-cred "00d3eee...e289b"

--> Following are deposit.json withdraw-cred when using launchpad eth2 deposit cli tool -- using same mnemonics as the ledger used above. <----
deposit.json index 0 - pubkey "8aa..d108" withdraw-cred "00d3eee...e289b"
deposit.json index 1 - pubkey "ab0..d025" withdraw-cred "00c8...0d889"
deposit.json index 2 - pubkey "83e..91c0" withdraw-cred "2c41...3ac82"
deposit.json index 3 - pubkey "8db..6665" withdraw-cred "4d35...2d5a3d"
==========================================

**Comment by robbtezos** [comment]
Some further conversation and feedback regarding this issue from reddit:

101ca7 1 point 9 hours ago 
Hi, thanks for replying and experimenting.

I looked through your github issues and you are correct that the issue lies with Ledger.

I was able to find the menmonic EIP spec here https://eips.ethereum.org/EIPS/eip-2334

And it clearly outlines that the withdrawal path is also incremented for each validator (which makes it impossible to have the same withdrawal key for different validators derived from the same mnemonic) it looks like Ledger has created a non conformant implementation.

I would strongly advise against using passphrases because of this. Of course you can generate the keystore and withdrawal keys either way but this non-conformance could cause a lot of headaches in the future.

permalinkembedsaveparentreportgive awardreplied

[–]tezonian[S] 1 point just now 
Hi, whether or not we use passphrases with ledger and launchpad tool, the same issue does persist of difference in withdrawal credentials of deposit.json files. -- when creating multiple validators in same deposit command.

Also another potential flag is that different heiarchical addresses in eth1 addresss space all point to same withdrawal public address and withdrawal credentials as seen by the ledger nano X app.

These issues have been detailed in the Github issue further elaborating some more differences in the keystore.json generated.. which I am not sure is either very significant or not.

**Comment by robbtezos** [comment]
As  pointed out by Ledger team, some of the 3rd party validator services are not sending the proper path for each validator index. 

You may want to check with your service provider if you choose to have unique credentials for their multiple validators created.

As further clarification, there is only a single eth2 withdrawal credential set based on the ledger mnemonic+passphrase . And the choice of the eth1 address (from the HD addresses) from which the eth2 credential is generated by the service provider or funds are sent does not matter.

All eth addresses belonging to same mnemonic+passphrase should generate the same withdrawal credential(s) as deposit-cli tool..
