### ISSUE TITLE
Prater release (v1.1.1) is missing checksum files

### ISSUE THREAD

**Issue by remyroy** [ethereum/eth2.0-deposit-cli#192]
[The prater release](https://github.com/ethereum/eth2.0-deposit-cli/releases/tag/v1.1.1) is missing checksum files compared to the previous releases. It is missing the *.sha256* files.

We are building tools to automate the validator setup in a simple one-click installer and we are validating the release file we are using with the checksum. If the checksum is missing, we'll have to stop this validation or try to parse the release description to find the checksum in there.

**Comment by hwwhww** [comment]
I just uploaded the .sha256 files to [the prater release](https://github.com/ethereum/eth2.0-deposit-cli/releases/tag/v1.1.1). Thank you for opening this issue!
