### ISSUE TITLE
Add support for the Kintsugi network

### ISSUE THREAD

**Issue by remyroy** [ethereum/eth2.0-deposit-cli#229]
It would be nice to add support for the Kintsugi network. The testnet details are in https://github.com/eth-clients/merge-testnets/tree/main/kintsugi . It seems like @avsetsin started working on it in https://github.com/lidofinance/eth2.0-deposit-cli/tree/kintsugi but I don't know where it's at now.

**Comment by djrtwo** [comment]
I think the next testnet is a good target. we'll be encouraging more and more users to try it out

**Comment by CarlBeek** [comment]
Kintsugi (and Kiln) support added via #240. Thanks regardless @remyroy!
