### ISSUE TITLE
Double-verify the merkle root with `remerkleable`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit-cli#23]
As discussed offline today, we can import `remerkleable` to double-verify the roots.
 
https://pypi.org/project/remerkleable/

Pros
- We can be more confident about the deposit message on deposit-cli side. Yay.

Cons
- `remerkleable` required Python 3.8+
- The contract will verify it anyway though
- It can be double-verify on the launchpad with https://github.com/ChainSafe/ssz (https://github.com/ethereum/eth2.0-deposit/issues/61) too

**Comment by CarlBeek** [comment]
Considering that it is verified in another two places already, I don't think it is worthwhile making this change.
