### ISSUE TITLE
./deposit.sh install failure on Mac OS

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-deposit-cli#52]
Running `./deposit.sh install` on Mac OS failed to install because of lack of write permissions in `/Library/Python/3.7`:

```
Installing collected packages: eth-hash, eth-typing, toolz, cytoolz, eth-utils, mypy-extensions, cached-property, py-ecc, pycryptodome, click, six, pyrsistent, lru-dict, ssz
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
Consider using the `--user` option or check the permissions.
```

That output was hidden in the middle of the install output though so I missed it initially.

Creating a `venv` and then rerunning `./deposit.sh install` worked correctly. ie:
```
python3 -m venv env
source env/bin/activate
./deposit.sh install
```

**Comment by CarlBeek** [comment]
Interesting. I don't even own a python3.7 at `/Library/Python` so I am personally unable to recreate the issue. That said I also use venvs everywhere to avoid these types of problems. The idea was to try to avoid requiring users to install Virtualenv if possible. (I thought it was built into python these days, but tests run on my server indicate otherwise. :/)

@hwwhww, do you have any bright ideas on how to solve this one?

**Comment by ajsutton** [comment]
I'm not really sure how I got a `/LibraryPython` my machine has a fairly long and sordid history.  It's possible that I'm just very special and this is a rare configuration problem but I don't know.

I also don't know how I got the env module installed...

**Comment by q9f** [comment]
Having a comparable issue on ArchLinux:

```
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/test-easy-install-40369.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.8/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by hwwhww** [comment]
@ajsutton @q9f could you help to test if `--user` flag works for you?

MacOS
```sh
pip install -r requirements.txt --user
python setup.py install
```

Linux
```
pip3 install -r requirements.txt --user
python3 setup.py install
```

**Comment by q9f** [comment]
pip install is working fine even without `--user`

`python3 setup.py install` fails with the error above.

**Comment by ilhanu** [comment]
> pip3 install -r requirements.txt --user

works

> python3 setup.py install

```
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-9231.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.8/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

I'm on ubuntu 20.04, user is in the sudo group

**Comment by alexfisher** [comment]
Can confirm I had same issue as @ilhanu on Ubuntu Server 20.04.  `python3 setup.py install --user` worked for me to complete the install.  Was then able to generate keys.

**Comment by q9f** [comment]
The following patch fixed it for me

https://gist.github.com/q9f/0f57fa13aa37279d1ba4c8b8e767241b

**Comment by hwwhww** [comment]
Maybe try virtualenv installation if it still doesn't work for you: https://github.com/ethereum/eth2.0-deposit-cli#option-3-build-deposit-cli-with-virtualenv

I'm closing it now. Let me know if you want to reopen it.
