### ISSUE TITLE
404 when reloading pages

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-deposit-cli#53]
I'd gotten through the acknowledgements before realising I'd need to switch browsers so I had Metamask available. When I copied the current URL (https://serene-carson-3331d5.netlify.app/generate-keys) to the other browser I got a 404 page.

Similarly reloading any page (e.g https://serene-carson-3331d5.netlify.app/congratulations) seems to give a 404.

This may just be related to how the current version is deployed but it would be nice if the URLs in the browser bar actually worked, even if they needed to use fragment identifiers instead of "real" paths.

**Comment by CarlBeek** [comment]
So this is partially intentional behaviour. The idea is that it is not possible to skip ahead in the process. It is intentional user friction to ensure that everyone goes through the steps. That said, it is not supposed to 404, it should just redirect you to the home page.

**Comment by CarlBeek** [comment]
Closing in favour of ethereum/eth2.0-deposit#111 so we can track the issue on the launchpad (website) side.
