### ISSUE TITLE
deposit.sh doesn't work with cygwin

### ISSUE THREAD

**Issue by ghost** [ethereum/eth2.0-deposit-cli#60]
```
User@Windows /home/user/eth2.0-deposit-cli
$ sh deposit.sh
deposit.sh: line 2: $'\r': command not found
deposit.sh: line 14: syntax error near unexpected token `elif'
deposit.sh: line 14: `elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin"']]; then
```

🤔

**Comment by ethers** [comment]
have you tried the windows exe (after unzip) at https://github.com/ethereum/eth2.0-deposit-cli/issues/67#issue-666482444 ?

**Comment by hwwhww** [comment]
Maybe try virtualenv installation or download binary file? https://github.com/ethereum/eth2.0-deposit-cli#option-3-build-deposit-cli-with-virtualenv-1

I'm closing it now. Let me know if you want to reopen it.
