### ISSUE TITLE
error installing Install deposit-cli dependencies  windows 10

### ISSUE THREAD

**Issue by msc82** [ethereum/eth2.0-deposit-cli#70]
msc82@DESKTOP-N12G70C MINGW64 /e/eth2.0-deposit-cli (master)
$ sh deposit.sh install
msys
Installing dependencies...
Collecting py-ecc==4.0.0
  Using cached py_ecc-4.0.0-py3-none-any.whl (41 kB)
Collecting pycryptodome==3.9.7
  Using cached pycryptodome-3.9.7-cp38-cp38-win32.whl (14.1 MB)
Collecting click==7.0
  Using cached Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting ssz==0.2.3
  Using cached ssz-0.2.3-py3-none-any.whl (43 kB)
Requirement already satisfied: eth-typing==2.2.1 in c:\users\msc82\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 41)) (2.2.1)
Collecting eth-utils==1.8.4
  Using cached eth_utils-1.8.4-py3-none-any.whl (23 kB)
Requirement already satisfied: mypy-extensions==0.4.3 in c:\users\msc82\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 49)) (0.4.3)
Collecting lru-dict==1.1.6
  Using cached lru-dict-1.1.6.tar.gz (9.4 kB)
Collecting pyrsistent==0.15.7
  Using cached pyrsistent-0.15.7.tar.gz (107 kB)
Requirement already satisfied: eth-hash==0.2.0 in c:\program files (x86)\python38-32\lib\site-packages (from -r requirements.txt (line 56)) (0.2.0)
Collecting cytoolz==0.10.1
  Using cached cytoolz-0.10.1.tar.gz (475 kB)
Requirement already satisfied: toolz==0.10.0 in c:\users\msc82\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 61)) (0.10.0)
Collecting six==1.14.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: cached-property==1.5.1 in c:\users\msc82\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 66)) (1.5.1)
Building wheels for collected packages: lru-dict, pyrsistent, cytoolz
  Building wheel for lru-dict (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\lru-dict\\setup.py'"'"'; __file__='"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\msc82\AppData\Local\Temp\pip-wheel-dh_o5iwn'
       cwd: C:\Users\msc82\AppData\Local\Temp\pip-install-1hbut51e\lru-dict\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  creating build
  creating build\temp.win32-3.8
  creating build\temp.win32-3.8\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\python38-32\include" "-Ic:\program files (x86)\python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" /Tclru.c /Fobuild\temp.win32-3.8\Release\lru.obj
  lru.c
  c:\program files (x86)\python38-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.15.7-cp38-cp38-win32.whl size=56526 sha256=3810c0d753020914362ebc3a388a7fc75848381e86b04889d8990aeca4bedd74
  Stored in directory: c:\users\msc82\appdata\local\pip\cache\wheels\be\48\69\322d0d62b8a2eb62b4b497b10c30902d0d2cb4599ca0d4e1ba
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\msc82\AppData\Local\Temp\pip-wheel-pwl4ox2k'
       cwd: C:\Users\msc82\AppData\Local\Temp\pip-install-1hbut51e\cytoolz\
  Complete output (60 lines):
  [1/5] Cythonizing cytoolz/utils.pyx
  [2/5] Cythonizing cytoolz/dicttoolz.pyx
  [3/5] Cythonizing cytoolz/functoolz.pyx
  [4/5] Cythonizing cytoolz/itertoolz.pyx
  [5/5] Cythonizing cytoolz/recipes.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  creating build\lib.win32-3.8\cytoolz
  copying cytoolz\compatibility.py -> build\lib.win32-3.8\cytoolz
  copying cytoolz\utils_test.py -> build\lib.win32-3.8\cytoolz
  copying cytoolz\_signatures.py -> build\lib.win32-3.8\cytoolz
  copying cytoolz\_version.py -> build\lib.win32-3.8\cytoolz
  copying cytoolz\__init__.py -> build\lib.win32-3.8\cytoolz
  creating build\lib.win32-3.8\cytoolz\curried
  copying cytoolz\curried\exceptions.py -> build\lib.win32-3.8\cytoolz\curried
  copying cytoolz\curried\operator.py -> build\lib.win32-3.8\cytoolz\curried
  copying cytoolz\curried\__init__.py -> build\lib.win32-3.8\cytoolz\curried
  copying cytoolz\dicttoolz.pyx -> build\lib.win32-3.8\cytoolz
  copying cytoolz\functoolz.pyx -> build\lib.win32-3.8\cytoolz
  copying cytoolz\itertoolz.pyx -> build\lib.win32-3.8\cytoolz
  copying cytoolz\recipes.pyx -> build\lib.win32-3.8\cytoolz
  copying cytoolz\utils.pyx -> build\lib.win32-3.8\cytoolz
  copying cytoolz\cpython.pxd -> build\lib.win32-3.8\cytoolz
  copying cytoolz\dicttoolz.pxd -> build\lib.win32-3.8\cytoolz
  copying cytoolz\functoolz.pxd -> build\lib.win32-3.8\cytoolz
  copying cytoolz\itertoolz.pxd -> build\lib.win32-3.8\cytoolz
  copying cytoolz\recipes.pxd -> build\lib.win32-3.8\cytoolz
  copying cytoolz\utils.pxd -> build\lib.win32-3.8\cytoolz
  copying cytoolz\__init__.pxd -> build\lib.win32-3.8\cytoolz
  creating build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\dev_skip_test.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_compatibility.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_curried.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_dicttoolz.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_docstrings.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_doctests.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_functoolz.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_inspect_args.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_itertoolz.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_none_safe.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_recipes.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_serialization.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_signatures.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_tlz.py -> build\lib.win32-3.8\cytoolz\tests
  copying cytoolz\tests\test_utils.py -> build\lib.win32-3.8\cytoolz\tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build\temp.win32-3.8
  creating build\temp.win32-3.8\Release
  creating build\temp.win32-3.8\Release\cytoolz
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\python38-32\include" "-Ic:\program files (x86)\python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" /Tccytoolz/dicttoolz.c /Fobuild\temp.win32-3.8\Release\cytoolz/dicttoolz.obj
  dicttoolz.c
  c:\program files (x86)\python38-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
Successfully built pyrsistent
Failed to build lru-dict cytoolz
Installing collected packages: cytoolz, eth-utils, py-ecc, pycryptodome, click, six, pyrsistent, lru-dict, ssz
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\msc82\AppData\Local\Temp\pip-record-zw5qp_n6\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files (x86)\python38-32\Include\cytoolz'
         cwd: C:\Users\msc82\AppData\Local\Temp\pip-install-1hbut51e\cytoolz\
    Complete output (60 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\_version.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\__init__.py -> build\lib.win32-3.8\cytoolz
    creating build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win32-3.8\cytoolz
    creating build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win32-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    creating build\temp.win32-3.8\Release\cytoolz
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\python38-32\include" "-Ic:\program files (x86)\python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" /Tccytoolz/dicttoolz.c /Fobuild\temp.win32-3.8\Release\cytoolz/dicttoolz.obj
    dicttoolz.c
    c:\program files (x86)\python38-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\msc82\\AppData\\Local\\Temp\\pip-install-1hbut51e\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\msc82\AppData\Local\Temp\pip-record-zw5qp_n6\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files (x86)\python38-32\Include\cytoolz' Check the logs for full command output.
running install
running bdist_egg
running egg_info
writing eth2deposit.egg-info\PKG-INFO
writing dependency_links to eth2deposit.egg-info\dependency_links.txt
writing top-level names to eth2deposit.egg-info\top_level.txt
file eth2deposit.py (for module eth2deposit) not found
reading manifest file 'eth2deposit.egg-info\SOURCES.txt'
writing manifest file 'eth2deposit.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
file eth2deposit.py (for module eth2deposit) not found
copying eth2deposit\deposit.py -> build\lib\eth2deposit
file eth2deposit.py (for module eth2deposit) not found
creating build\bdist.win32\egg
creating build\bdist.win32\egg\eth2deposit
copying build\lib\eth2deposit\credentials.py -> build\bdist.win32\egg\eth2deposit
copying build\lib\eth2deposit\deposit.py -> build\bdist.win32\egg\eth2deposit
creating build\bdist.win32\egg\eth2deposit\key_handling
copying build\lib\eth2deposit\key_handling\keystore.py -> build\bdist.win32\egg\eth2deposit\key_handling
creating build\bdist.win32\egg\eth2deposit\key_handling\key_derivation
copying build\lib\eth2deposit\key_handling\key_derivation\mnemonic.py -> build\bdist.win32\egg\eth2deposit\key_handling\key_derivation
copying build\lib\eth2deposit\key_handling\key_derivation\path.py -> build\bdist.win32\egg\eth2deposit\key_handling\key_derivation
copying build\lib\eth2deposit\key_handling\key_derivation\tree.py -> build\bdist.win32\egg\eth2deposit\key_handling\key_derivation
copying build\lib\eth2deposit\key_handling\key_derivation\__init__.py -> build\bdist.win32\egg\eth2deposit\key_handling\key_derivation
copying build\lib\eth2deposit\key_handling\__init__.py -> build\bdist.win32\egg\eth2deposit\key_handling
copying build\lib\eth2deposit\settings.py -> build\bdist.win32\egg\eth2deposit
creating build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\utils\ascii_art.py -> build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\utils\constants.py -> build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\utils\crypto.py -> build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\utils\ssz.py -> build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\utils\validation.py -> build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\utils\__init__.py -> build\bdist.win32\egg\eth2deposit\utils
copying build\lib\eth2deposit\__init__.py -> build\bdist.win32\egg\eth2deposit
creating build\bdist.win32\egg\tests
creating build\bdist.win32\egg\tests\test_key_handling
copying build\lib\tests\test_key_handling\test_keystore.py -> build\bdist.win32\egg\tests\test_key_handling
creating build\bdist.win32\egg\tests\test_key_handling\test_key_derivation
copying build\lib\tests\test_key_handling\test_key_derivation\test_mnemonic.py -> build\bdist.win32\egg\tests\test_key_handling\test_key_derivation
copying build\lib\tests\test_key_handling\test_key_derivation\test_path.py -> build\bdist.win32\egg\tests\test_key_handling\test_key_derivation
copying build\lib\tests\test_key_handling\test_key_derivation\test_tree.py -> build\bdist.win32\egg\tests\test_key_handling\test_key_derivation
copying build\lib\tests\test_key_handling\test_key_derivation\__init__.py -> build\bdist.win32\egg\tests\test_key_handling\test_key_derivation
copying build\lib\tests\test_key_handling\__init__.py -> build\bdist.win32\egg\tests\test_key_handling
byte-compiling build\bdist.win32\egg\eth2deposit\credentials.py to credentials.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\deposit.py to deposit.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\key_handling\keystore.py to keystore.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\key_handling\key_derivation\mnemonic.py to mnemonic.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\key_handling\key_derivation\path.py to path.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\key_handling\key_derivation\tree.py to tree.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\key_handling\key_derivation\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\key_handling\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\settings.py to settings.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\utils\ascii_art.py to ascii_art.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\utils\constants.py to constants.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\utils\crypto.py to crypto.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\utils\ssz.py to ssz.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\utils\validation.py to validation.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\utils\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win32\egg\eth2deposit\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win32\egg\tests\test_key_handling\test_keystore.py to test_keystore.cpython-38.pyc
byte-compiling build\bdist.win32\egg\tests\test_key_handling\test_key_derivation\test_mnemonic.py to test_mnemonic.cpython-38.pyc
byte-compiling build\bdist.win32\egg\tests\test_key_handling\test_key_derivation\test_path.py to test_path.cpython-38.pyc
byte-compiling build\bdist.win32\egg\tests\test_key_handling\test_key_derivation\test_tree.py to test_tree.cpython-38.pyc
byte-compiling build\bdist.win32\egg\tests\test_key_handling\test_key_derivation\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win32\egg\tests\test_key_handling\__init__.py to __init__.cpython-38.pyc
creating build\bdist.win32\egg\EGG-INFO
copying eth2deposit.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying eth2deposit.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying eth2deposit.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying eth2deposit.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\eth2deposit-0.2.0-py3.8.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing eth2deposit-0.2.0-py3.8.egg
Removing c:\program files (x86)\python38-32\lib\site-packages\eth2deposit-0.2.0-py3.8.egg
Copying eth2deposit-0.2.0-py3.8.egg to c:\program files (x86)\python38-32\lib\site-packages
eth2deposit 0.2.0 is already the active version in easy-install.pth

Installed c:\program files (x86)\python38-32\lib\site-packages\eth2deposit-0.2.0-py3.8.egg
Processing dependencies for eth2deposit==0.2.0
Finished processing dependencies for eth2deposit==0.2.0

msc82@DESKTOP-N12G70C MINGW64 /e/eth2.0-deposit-cli (master)
$ sh deposit.sh
msys
Running deposit-cli...
Traceback (most recent call last):
  File "./eth2deposit/deposit.py", line 3, in <module>
    import click
ModuleNotFoundError: No module named 'click'

msc82@DESKTOP-N12G70C MINGW64 /e/eth2.0-deposit-cli (master)

**Comment by ethers** [comment]
have you tried the windows exe (after unzip) at https://github.com/ethereum/eth2.0-deposit-cli/issues/67#issue-666482444 ?

**Comment by developerfred** [comment]
Hey @msc82! create a gist with your log and post the link, it is easier to understand the problem

**Comment by msc82** [comment]
Hej ! i ve tried binaries and it works thank you @ethers !

**Comment by swkim109** [comment]
I have same issues on Windows 10 64bit.

I was running into several "ModuleNotFoundError"(click, Crypto, and so on).
It seems that the proper windows-build-tools(Microsoft Visual C++ 14) should be installed and then run `sh deposit.sh install` in Git bash shell(right click on the git clone directory). 

If you have still "ModuleNotFoundError: No module name Crypto", need to do some modification of crypto.py. I am **NOT** a Python guy but with googling, I added the following snippet to the file:

```
import crypto
import sys
sys.module['Crypto'] = crypto

```
I think you can run deposit-cli without error. But when I typed password at "Type the password that secures your validator keystore(s):", nothing happens. It seems pending or stuck. 

I'm not sure this is the solution and still far away from the validator...

**Comment by hwwhww** [comment]
@swkim109  does the binaries work for you? https://github.com/ethereum/eth2.0-deposit-cli/releases/tag/v0.4.1

I'm closing it now, let me know you want to reopen it or send a new issue.
