### ISSUE TITLE
Import error when using Python3 from Microsoft Store on Windows

### ISSUE THREAD

**Issue by Magicking** [ethereum/eth2.0-deposit-cli#72]
When using the Python3 from error, an import error about not finding the eth2deposit module when started.

```PS C:\Users\Smith\Downloads\eth2.0-deposit-cli-master\eth2.0-deposit-cli-master> python3 .\eth2deposit\deposit.py
Traceback (most recent call last):
  File ".\eth2deposit\deposit.py", line 5, in <module>
    from eth2deposit.credentials import (
ModuleNotFoundError: No module named 'eth2deposit'
```

See for full log https://gist.github.com/Magicking/9c059ea5240f96729361072ac847aed1

**Comment by hwwhww** [comment]
@Magicking 
I think you missed to run `python setup.py install` before calling `python.exe .\eth2deposit\deposit.py`.
