### ISSUE TITLE
ModuleNotFoundError: No module named 'py_ecc' 

### ISSUE THREAD

**Issue by davidfrothin** [ethereum/eth2.0-deposit-cli#78]
Followed all steps and have ubuntu 18.04 with
python3.7 --version
Python 3.7.8
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.7)

git clone https://github.com/ethereum/eth2.0-deposit-cli.git
cd eth2.0-deposit-cli
pip3 install -r requirements.txt
python3.7 setup.py install
#all above worked without issues

python3.7 ./eth2deposit/deposit.py --num_validators 1 --chain medalla

Traceback (most recent call last):
File "./eth2deposit/deposit.py", line 5, in
from eth2deposit.credentials import (
File "/usr/local/lib/python3.7/dist-packages/eth2deposit-0.2.1-py3.7.egg/eth2deposit/credentials.py", line 5, in
from py_ecc.bls import G2ProofOfPossession as bls
ModuleNotFoundError: No module named 'py_ecc'

**Comment by piotrbednarczyk** [comment]
I had similar issue a moment ago. Do you have any compilation errors while executing  ` pip3 install -r requirements.txt` ?
In my case it helped when I installed headers and static libs in correct version. For you it should probably be `sudo apt-get install python3.7-dev`. Then try to rebuild.

**Comment by davidfrothin** [comment]
Thanks, that helps
