### ISSUE TITLE
Regenerate keys from mnemonic

### ISSUE THREAD

**Issue by calumtomeny** [ethereum/eth2.0-deposit-cli#80]
I was wondering how I can recreate the deposit file and validator keys from the mnemonic - Is this a supported feature?

**Comment by gasolin** [comment]
dup of #29

**Comment by calumtomeny** [comment]
If this feature doesn't get implemented what is the best workaround for recreating the validator keys if, for some reason, you lose access to your validator keys but you still have access to your seed phrase?

**Comment by mratsim** [comment]
Note that due to https://github.com/ethereum/eth2.0-deposit-cli/pull/108 you will have to use an old version of the deposits CLI to rederive your keys from the mnemonic.

**Comment by calumtomeny** [comment]
I suppose due to #108 it will be unlikely for the mnemonic to validator private key process to change again so it would be nice to be able to regenerate the keys without having to modify the code in deposit.py. Replacing `get_mnemonic` on line 30 with a mnemonic.

**Comment by hwwhww** [comment]
closing via #123
